### ISSUE TITLE
No file named -- run_partial.py

### ISSUE THREAD

**Issue by AadSah** [tim-learn/BA3US#1]

**Comment by tim-learn** [comment]
Hi, thanks for your interest, we would like to upload the main file after the ECCV conference, maybe several weeks later.

**Comment by tim-learn** [comment]
> _No description provided._

Hi, thanks for your interest, we would like to upload the main file after the ECCV conference, maybe several weeks later.

**Comment by abutaufique** [comment]
Hi, when will you make the run_partial.py available?

**Comment by tim-learn** [comment]
@AadSah @abutaufique Sorry for the delay due to some personal matters. I have uploaded the main file, you can play with it now.
