### ISSUE TITLE
Baseline experiments clarification

### ISSUE THREAD

**Issue by ShaniGam** [tim-learn/BA3US#3]
Great work!
I'm looking at the experiments in the paper and I'm a bit confused. As far as I understand, your source consists of examples from the source distribution+(fewer) examples from the target distribution. If that's the case, does the ResNet-50 baseline also includes examples from the target distribution or only examples from the source distribution?

**Comment by tim-learn** [comment]
Hi, @ShaniGam 

The ResNet-50 baseline is a source-only method that does not include examples from the target distribution.

Best

Tim

**Comment by ShaniGam** [comment]
Did you compare your work to a network that was trained on the same exact data (source+partial target)?

**Comment by tim-learn** [comment]
@ShaniGam  Since the target data is unlabeled, it is hard to find a solution to use it during supervised training with source data. Our paper aims to include the target data into the source domain during alignment instead of classification.

**Comment by ShaniGam** [comment]
I thought you used some labeled data for training in your method but I guess I was wrong. thanks.
