### ISSUE TITLE
Implementation for Close-set Domain Adaptation

### ISSUE THREAD

**Issue by LearnableVW** [tim-learn/BA3US#4]
Hi Tim Team, I'm a bit confused about the results of the vanilla domain adaptation (Table 4). How could I get the results for the w/BAA and BA3US model? And could you also explain a little on your implementation of BA3US + CDAN model (last line). Thanks!

**Comment by tim-learn** [comment]
> Hi Tim Team, I'm a bit confused about the results of the vanilla domain adaptation (Table 4). How could I get the results for the w/BAA and BA3US model? And could you also explain a little on your implementation of BA3US + CDAN model (last line). Thanks!

Hi, there

1. You can change the target text list in the code for closed-set UDA.
2. You can replace the adversarial loss with that in the code of CDAN.

**Comment by ALshore33** [comment]
Thanks for replying. I will tried it out.

**Comment by LearnableVW** [comment]
Thanks for replying. I will tried it out.
