### ISSUE TITLE
Some questions about A Balanced and Uncertainty-aware Approach for Partial Domain Adaptation

### ISSUE THREAD

**Issue by LYX1637** [tim-learn/BA3US#5]
1. If choose the samples which belong to the missing class in target domain, what will happen?
2. Since the samples of the source domain are randomly selected, will it cause the problem of inconsistency of the categories?

**Comment by tim-learn** [comment]
> 1. If choose the samples which belong to the missing class in target domain, what will happen?
> 2. Since the samples of the source domain are randomly selected, will it cause the problem of inconsistency of the categories?

We just randomly select the source samples in the experiment to increase the balance across domains, and the number of samples chosen is gradually decreasing during the training process.
